apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: "{{ .Values.controller.image }}"
        ports:
        - containerPort: 8080
        - containerPort: 50000
        resources:
          requests:
            memory: "{{ .Values.controller.resources.requests.memory }}"
            cpu: "{{ .Values.controller.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.controller.resources.limits.memory }}"
            cpu: "{{ .Values.controller.resources.limits.cpu }}"
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-pvc
